
// This file has been generated by the GUI designer. Do not modify.
namespace Roadplus.Server.UI
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action addAction;
		
		private global::Gtk.Action SettingsAction;
		
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Notebook notebook4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Fixed fixed4;
		
		private global::Gtk.Label Test;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Fixed fixed3;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry tbSchoolName;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.ComboBox combobox2;
		
		private global::Gtk.ComboBox combobox1;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.Label label4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Roadplus.Server.UI.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.addAction = new global::Gtk.Action ("addAction", global::Mono.Unix.Catalog.GetString ("Add"), null, "gtk-add");
			this.addAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add");
			w1.Add (this.addAction, null);
			this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
			this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.SettingsAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Roadplus.Server.UI.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Roadplus.Server.UI.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.notebook4 = new global::Gtk.Notebook ();
			this.notebook4.WidthRequest = 650;
			this.notebook4.HeightRequest = 301;
			this.notebook4.CanFocus = true;
			this.notebook4.Name = "notebook4";
			this.notebook4.CurrentPage = 2;
			// Notebook tab
			global::Gtk.Label w2 = new global::Gtk.Label ();
			w2.Visible = true;
			this.notebook4.Add (w2);
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
			this.notebook4.SetTabLabel (w2, this.label5);
			this.label5.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.notebook4.Add (this.fixed4);
			global::Gtk.Notebook.NotebookChild w3 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.fixed4]));
			w3.Position = 1;
			// Notebook tab
			this.Test = new global::Gtk.Label ();
			this.Test.Name = "Test";
			this.Test.LabelProp = global::Mono.Unix.Catalog.GetString ("Road Constructions");
			this.notebook4.SetTabLabel (this.fixed4, this.Test);
			this.Test.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.WidthRequest = 200;
			this.frame3.HeightRequest = 270;
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Start Time");
			this.fixed3.Add (this.label8);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label8]));
			w4.X = 9;
			w4.Y = 66;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.tbSchoolName = new global::Gtk.Entry ();
			this.tbSchoolName.CanFocus = true;
			this.tbSchoolName.Name = "tbSchoolName";
			this.tbSchoolName.IsEditable = true;
			this.tbSchoolName.InvisibleChar = '●';
			this.fixed3.Add (this.tbSchoolName);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.tbSchoolName]));
			w5.X = 3;
			w5.Y = 28;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("School Name");
			this.fixed3.Add (this.label7);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label7]));
			w6.X = 6;
			w6.Y = 8;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("0"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("15"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("20"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("25"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("30"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("35"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("40"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("45"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("50"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("55"));
			this.combobox2.AppendText ("");
			this.combobox2.Name = "combobox2";
			this.fixed3.Add (this.combobox2);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.combobox2]));
			w7.X = 78;
			w7.Y = 92;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("0"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("11"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("12"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("13"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("14"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("15"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("16"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("17"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("18"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("19"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("20"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("21"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("22"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("23"));
			this.combobox1.AppendText (global::Mono.Unix.Catalog.GetString ("24"));
			this.combobox1.Name = "combobox1";
			this.fixed3.Add (this.combobox1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.combobox1]));
			w8.X = 13;
			w8.Y = 91;
			this.GtkAlignment.Add (this.fixed3);
			this.frame3.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Add School</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel1;
			this.fixed2.Add (this.frame3);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.frame3]));
			w11.X = 4;
			w11.Y = 6;
			this.notebook4.Add (this.fixed2);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.fixed2]));
			w12.Position = 2;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Schools");
			this.notebook4.SetTabLabel (this.fixed2, this.label4);
			this.label4.ShowAll ();
			this.fixed1.Add (this.notebook4);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.notebook4]));
			w13.X = 3;
			w13.Y = 4;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 655;
			this.DefaultHeight = 308;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
