#!/bin/sh

# httpd service

start() {
	echo -n "Starting httpd"
	start-stop-daemon -S -q -p /var/run/httpd.pid \
		--exec /usr/sbin/httpd -- -h /var/www/
}

stop() {
	echo -n "Stopping httpd"
	start-stop-daemon -K -q -p /var/run/httpd.pid
	[ $? = 0 ] && echo "succes" || echo "failed"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
